# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  line-bot-sample

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    OpenApiVersion: 3.0.1

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  webhook:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - DataTraceEnabled: true
          LoggingLevel: 'INFO'
          ResourcePath: '/*'
          HttpMethod: '*'
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: LINE bot sample
          version: '1.0'
          description: 'LINE botのサンプル'
        servers: []
        paths:
          /callback:
            post:
              summary: LINEプラットフォームからのWebhookを受け取ってメッセージを送信します。
              operationId: post-callback
              responses:
                '200':
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          message:
                            type: string
                            description: メッセージ
                        required:
                          - message
                      examples:
                        example:
                          value:
                            message: success
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/line-webhook-sample.fifo'
                credentials: !Sub 'arn:aws:iam::${AWS::AccountId}:role/api-gateway-sqs-sendMessage'
                responses:
                  default:
                    statusCode: '200'
                passthroughBehavior: when_no_templates
                httpMethod: POST
                requestParameters:
                  integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
                requestTemplates:
                  application/json: 'Action=SendMessage&MessageGroupId=lineWebhook&MessageAttribute.1.Name=line-signature&MessageAttribute.1.Value.StringValue=$util.urlEncode($input.params().header.X-Line-Signature)&MessageAttribute.1.Value.DataType=String&MessageBody=$util.urlEncode($input.body)'
                type: aws
              description: LINEプラットフォームからのWebhookに対するcallback

  queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: line-webhook-sample.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 100

  lineBotLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/line-bot.lineBotHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: LINE bot sample
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt queue.Arn
            BatchSize: 10

  DB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String
      TableName: line-user-test