# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  line-bot-sample

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    OpenApiVersion: 3.0.1

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  lineBotLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/line-bot.lineBotHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: LINE bot sample
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: '/callback'
            RestApiId: !Ref webhook

  webhook:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - DataTraceEnabled: true
          LoggingLevel: 'INFO'
          ResourcePath: '/*'
          HttpMethod: '*'
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: LINE bot sample
          version: '1.0'
          description: 'LINE botのサンプル'
        servers: []
        paths:
          /callback:
            post:
              summary: LINEプラットフォームからのWebhookを受け取ってメッセージを送信します。
              operationId: post-callback
              responses:
                '200':
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          message:
                            type: string
                            description: メッセージ
                        required:
                          - message
                      examples:
                        example:
                          value:
                            message: success
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lineBotLambdaFunction.Arn}/invocations'
                responses:
                  default:
                    statusCode: '200'
                passthroughBehavior: when_no_match
                httpMethod: POST
                contentHandling: CONVERT_TO_TEXT
                type: aws_proxy
              description: LINEプラットフォームからのWebhookに対するcallback

